# COMMENTS:
# 
# 
# ENZR_TestSet_Mol_1


# Project configuration
target_cpd: 'CCC[C@H](CC#N)CC(=O)O'
project_name: 'ENZR_TestSet_Mol_1'
Resume_predictions_from_path: ''

# General settings:
min_solved_routes: 2000         # Number of solved routes to reach to stop teh search
max_iteration: 200              # Max number of iteration search (recommended min 20)
max_mol_per_iteration: 5        # max number of molecules to extend per iteration
Commercial_exclusions: ['']     # List of molecular SMILES to exclude from the commercial set
step_penalties_rate: 0.8        # Score penalty applied for each step
tmp_file_path: 'tmp/'           # Folder in which storing onmt prediction files
log: True                       # Enables logs
commercial_file_path: 'stocks/Commercial_canonical_2023_single_mol.smi' # List of target commercial compounds

# Tagging settings
mark_count: 3                   # Max number of atoms to tag
neighbors: True                 # Tag neighboring atoms only or not
Random_Tagging: True            # Enables exhaustive/random tagging
AutoTagging: True               # Enables Transformer-based tagging
AutoTagging_Beam_Size: 50       # Number of tags to generate by the tagging Transformer
Substructure_Tagging: True      # Enable tagging by matching substructure
list_substructures_path: 'stocks/list_conditionnal_substructures_tags_R2.csv'
list_substr_path_ENZR: 'stocks/list_conditionnal_substructures_tags_ENZR_R2.csv'

# USPTO Retrosynthesis parameters:
Retro_USPTO: True               # Enables USPTO T1 model
Fwd_USPTO_Reag_Pred: True       # Enables USPTO T3 model

# ENZR Retrosynthesis parameters:
Retro_ENZR: True                # Enables ENZR T1 model
Fwd_ENZ_Reag_Pred: True         # Enables ENZR T3 model
ENZR_confidence_threshold: 0.9  # T3 Confidence threshold under which the predictions are discarded

# Beam sizes:
Retro_beam_size: 3              # Number of set of precursors to predict per molecule
USPTO_Reag_Beam_Size: 2         # Beam size (number of) reactant sets to predict (T2) and try on T3

# Tree search performance settings:
mark_locations_filter: 1        # percentage of tags to keep, randomly selected, use for large molecules
tree_only_best: 0.75            # percentage of overall branches to keep after an iteration
tree_min_best: 5000             # min number of branches to keep after an iteration
tree_max_best: 50000            # max number of branches to keep after an iteration
branching_max_expansion: 15     # max number of branching per molecule (node, best score first)

# Transformer model paths:
Model_Folder:       'models/'   # Folder path containing Transformer models

# Transformer model paths, USPTO:
USPTO_AutoTag_path: 'USPTO_STEREO_separated_T0_AutoTag_260000.pt'
USPTO_T1_path:      'USPTO_STEREO_separated_T1_Retro_255000.pt'
USPTO_T2_path:      'USPTO_STEREO_separated_T2_Reagent_Pred_225000.pt'
USPTO_T3_path:      'USPTO_STEREO_separated_T3_Forward_255000.pt'

# Transformer model paths, ENZR:
ENZR_AutoTag_path:  ''
ENZR_T1_path:       'T1_ENZR_USPTO_step_275000.pt'
ENZR_T2_path:       'T2_ENZR_USPTO_step_295000.pt'
ENZR_T3_path:       'T3_ENZR_USPTO_step_285000.pt'

# Prediction filters (do not use):
similarity_filter: False        # Filters out retrosynthesis predictions too similar to the target 
confidence_filter: False        # Filters out low T3 confident predictions

